import type { Figure, FigureFit } from "./figure.js";

export type PrimitiveRichText = string | MarkdownText;

export type MarkdownText = {
  kind: "markdown";
  value: string;
};

export type TemplateField = {
  id: string;
  type: "text" | "image";
  shapeId: string;
  name: string;
  originalText: string;
  x?: number;
  y?: number;
  w?: number;
  h?: number;
  preserveStyleByDefault: boolean;
  /**
   * Marks a field the deck owns rather than the author. A `page-number` field is
   * rewritten as a live PowerPoint slide-number field at build time, so it is
   * never listed as a fillable variable.
   */
  role?: "page-number";
};

export type FieldsFile = {
  templateId: string;
  librarySlide: number;
  fields: TemplateField[];
};

export type TemplateMetadata = {
  id: string;
  name: string;
  kind: "cloned-slide";
  status: "draft" | "ready";
  version: string;
  source: {
    deck: string;
    slide: number;
    importedOn: string;
  };
  fonts: string[];
  variables: string[];
  tags: string[];
};

export type SlideVariables = Record<string, PrimitiveRichText>;

export type SlideOverride =
  | { op: "delete"; target: string }
  | { op: "hide"; target: string }
  | { op: "move"; target: string; x: number; y: number }
  | { op: "resize"; target: string; w: number; h: number }
  | { op: "styleText"; target: string; fontSize?: number; color?: string; fontFace?: string }
  | {
      op: "addText";
      id: string;
      text: PrimitiveRichText;
      x: number;
      y: number;
      w: number;
      h: number;
      style?: TextStyle;
    }
  | { op: "addSvg"; id: string; path: string; x: number; y: number; w: number; h: number }
  | { op: "addIcon"; id: string; icon: string; x: number; y: number; w: number; h: number; color?: string }
  | ({ op: "replaceImage"; target: string; fit?: ImageFit } & ImageSource)
  | ({ op: "addImage"; id: string; x: number; y: number; w: number; h: number; fit?: ImageFit } & ImageSource)
  | { op: "addFigure"; id: string; figure: Figure; x: number; y: number; w: number; h: number; fit?: FigureFit }
  | { op: "replaceFigure"; target: string; figure: Figure; fit?: FigureFit };

/**
 * Where a picture comes from: a file in the deck's folder, or an image declared
 * in the brief's `## Images` block (generated by `pptx-gen images`, or dropped
 * into `inputs/` by hand).
 *
 * A missing `path` is an authoring error and fails the build. A missing
 * `image` is expected — it has not been generated yet — so it becomes a
 * captioned placeholder and a warning instead.
 */
export type ImageSource = { path: string; image?: never } | { image: string; path?: never };

/**
 * How a picture fills its box. `cover` crops to fill it, `contain` shrinks the
 * box to the picture's shape, `stretch` distorts. An `image` defaults to
 * `cover`; a `path` keeps its long-standing behaviour (stretch into the box,
 * or a straight swap for `replaceImage`) unless a fit is given.
 */
export type ImageFit = "cover" | "contain" | "stretch";

export type TextStyle = {
  fontFace?: string;
  fontSize?: number;
  color?: string;
  bold?: boolean;
  italic?: boolean;
};

export type AddSlideOptions = {
  templateName: string;
  variables?: SlideVariables;
  overrides?: SlideOverride[];
  /**
   * Optional variant-group id. Slides sharing a group are alternative
   * renderings of the same concept, listed together in the build report so the
   * reviewer can pick one. Variants of a group must be added consecutively.
   */
  group?: string;
};

export type TemplateDeckSlide = {
  kind: "template";
  options: AddSlideOptions;
};

export type CustomDeckSlide = {
  kind: "custom";
  slide: import("./custom-slide.js").CustomSlide;
};

export type DeckSlide = TemplateDeckSlide | CustomDeckSlide;

export type RenderOptions = {
  output: string;
  report?: string;
  screenshots?: string;
  /** Where figure HTML and PNGs are written. Defaults to `figures/` beside the output. */
  figures?: string;
  /** Show live, timed build progress in the terminal. Defaults to true. */
  progress?: boolean;
};

/** What became of one figure in a build. */
export type FigureRecord = {
  id: string;
  /** `placeholder` means it could not be rendered and a captioned box was drawn. */
  status: "rendered" | "cached" | "placeholder";
  htmlPath: string;
  pngPath?: string;
  pxWidth?: number;
  pxHeight?: number;
  reason?: string;
};

/** What became of one picture placed through `addImage` or `replaceImage`. */
export type ImageRecord = {
  /** The brief's image id, for an `image` source. */
  id?: string;
  /** The file placed, relative to the deck folder when inside it. */
  path?: string;
  /** 1-based position in the output deck. */
  slide: number;
  /** `placeholder` means there was no file yet and a captioned box was drawn. */
  status: "placed" | "placeholder";
  reason?: string;
};

export type BuildWarning = {
  code: string;
  message: string;
  slide?: number;
  target?: string;
};

export type BuildReportSlide = {
  /** 1-based position in the output deck. */
  index: number;
  kind: "template" | "custom";
  /** Template id for template slides, the CustomSlide name for custom slides. */
  name: string;
  /** Variant-group id, when this slide is one of several variants of a concept. */
  group?: string;
  /** 1-based position within the group. Set only when `group` is set. */
  variant?: number;
  /** Total slides in this group. Set only when `group` is set. */
  variantCount?: number;
};

export type BuildReport = {
  generatedAt: string;
  output: string;
  templatesUsed: string[];
  customSlidesUsed: string[];
  /** Every slide in output order, with variant-group membership. */
  slides: BuildReportSlide[];
  slidesBuilt: number;
  warnings: BuildWarning[];
  screenshots: string[];
  figures: FigureRecord[];
  images: ImageRecord[];
};
